service: tattoo-directory-backend
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-2
  stage: ${opt:stage, 'dev'}
  environment:
    TABLE_NAME: ${self:service}-${sls:stage}-TattooDirectory
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:provider.environment.TABLE_NAME}
        - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:provider.environment.TABLE_NAME}/index/*

functions:
  getArtist:
    handler: src/handlers/getArtist.handler
    events:
      - httpApi:
          method: GET
          path: /artist/{id}

  listArtists:
    handler: src/handlers/listArtists.handler
    events:
      - httpApi:
          method: GET
          path: /artists

  getArtistsByStyles:
    handler: src/handlers/getArtistsByStyles.handler
    events:
      - httpApi:
          method: GET
          path: /artists/{styles} # styles is comma-separated

  updateArtist:
    handler: src/handlers/updateArtist.handler
    events:
      - httpApi:
          method: PATCH
          path: /artist/{id}

  postRemovalRequest:
    handler: src/handlers/postRemovalRequest.handler
    events:
      - httpApi:
          method: POST
          path: /removal-requests

resources:
  Resources:
    TattooDirectoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: gsi1pk
            AttributeType: S
          - AttributeName: gsi1sk
            AttributeType: S
          - AttributeName: gsi2pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: EntityIndex
            KeySchema:
              - AttributeName: gsi1pk
                KeyType: HASH
              - AttributeName: gsi1sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: InstagramIndex
            KeySchema:
              - AttributeName: gsi2pk
                KeyType: HASH
            Projection:
              ProjectionType: KEYS_ONLY
